apiVersion: aspool.nddr.yndd.io/v1alpha1
kind: Alloc
metadata:
  name: alloc1
  namespace: default
  annotations:
    src-tag/node: leaf1
    src-tag/network-instance: default
    src-tag/tenant: default
spec:
  alloc:
    as-pool-name: default
      
